apiVersion: 1

contactPoints:
    - orgId: 1
      name: scriptio-email
      receivers:
          - uid: scriptio-email
            type: email
            settings:
                addresses: hugo.bois@hotmail.fr
                singleEmail: true
