name: Build Windows MSIX

on:
    push:
        branches: [dev]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '25.2.1'
          cache: 'pnpm'

      - name: Setup Rust
        uses: dtolnay/rust-action@stable
        with:
          targets: x86_64-pc-windows-msvc, aarch64-pc-windows-msvc

      - name: Install dependencies
        run: pnpm install

      - name: Build MSIX bundle
        run: pnpm tauri:windows:build