name: Build & Deploy MacOS

on:
    push:
        branches: [release]

jobs:
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v6

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "25.2.1"

            - name: Setup Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: aarch64-apple-darwin, x86_64-apple-darwin

            - name: Install dependencies
              run: npm install

            - name: Build MacOS bundle
              run: npm tauri:build:macos

            - name: Upload to App Store Connect
              run: |
                  xcrun altool --upload-package \
                    --file "Scriptio.pkg" \
                    --type osx \
                    --apiKey "${{ secrets.APPSTORE_KEY_ID }}" \
                    --apiIssuer "${{ secrets.APPSTORE_ISSUER_ID }}"
