name: Build & Deploy Web

on:
    push:
        branches: [release]

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v6

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build image
              run: docker compose build app

            - name: Push image to GHCR
              run: docker push ghcr.io/lycoon/scriptio-app:latest

    deploy:
        runs-on: ubuntu-latest
        needs: build_and_push
        steps:
            - name: Checkout repo
              uses: actions/checkout@v6

            - name: Copy docker-compose to VPS
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_SECRET }}
                  port: ${{ secrets.SSH_PORT }}
                  source: docker-compose.yml
                  target: ${{ secrets.APP_PATH }}

            - name: Deploy via SSH
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_SECRET }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd ${{ secrets.APP_PATH }}
                      docker compose pull app
                      docker compose --profile prod up -d
